# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        build:
            context: ../docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '50000:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres
    postgres:
        image: postgres:14.5-alpine
        ports:
            - '50001:5432'
        environment:
            - POSTGRES_PASSWORD=1234
        volumes:
            - ./../postgres:/var/lib/postgresql/data
        networks:
            - sail
networks:
    sail:
        driver: bridge
